### ISSUE TITLE
Redundant code

### ISSUE THREAD

**Issue by AlfieC** [KohiNetwork/TcpNoDelayMod#4]
yo

`ClientConnectedToServerEvent -> Minecraft.getMinecraft().getNetHandler().getNetworkManager().channel().config().setOption(ChannelOption.TCP_NODELAY, true);`

thank me l8r

**Comment by AlfieC** [comment]
you'll have to check that the network manager isn't null & do it when the player is actually connected to the server

**Comment by AlfieC** [comment]
oh also needs forge

**Comment by prplz** [comment]
Yeah I chose not to use forge so it could support all mc versions with one jar.

**Comment by AlfieC** [comment]
You could use the way you're using now to get the NetworkManager and just reflect to get the Channel - would be faster than your current method and a third of the size.
