### ISSUE TITLE
Virus?

### ISSUE THREAD

**Issue by Airzonegithub** [KohiNetwork/TcpNoDelayMod#8]
I am getting this mod for anarchy mc so I dont get high ping. 
Is this trust worthy? I had looked into the src and god it looks dodgy

**Comment by dynamicdiscord** [comment]
If you think it's dodgy don't use it. The end.

if you think it's dodgy, none of us can change your mind. This is a pretty common mod nowadays but you can do the same via regedit instead of this mod.

**Comment by prplz** [comment]
You got me
